kind: Pod
apiVersion: v1
metadata:
  name: busybox-dnstest
spec:
  containers:
    - name: busybox
      image: radial/busyboxplus:curl
      command: ['sh', '-c', 'while true; do sleep 3600; done']
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-dnstest
spec:
  containers:
    - name: nginx
      image: nginx:1.19.2
      ports:
        - containerPort: 80
