apiVersion: v1
kind: Pod
metadata:
  labels:
    env: home
  name: dotnet-app
spec:
  containers:
  - image: mcr.microsoft.com/dotnet/samples:aspnetapp
    name: dotnet-app
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
