# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  name: nodeport01
  namespace: default
spec:
  type: NodePort
  ports:
  - nodePort: 30087
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: svc-example
