kind: Service
apiVersion: v1
metadata:
  name: shipping-svc
spec:
  selector:
    app: shipping-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: shipping-backend
  labels:
    app: shipping-svc
spec:
  containers:
    - name: nginx
      image: nginx:1.19.1
