kind: Service
apiVersion: v1
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: svc-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
