apiVersion: v1
kind: Service
metadata:
  name: svc-temp
spec:
  type: NodePort
  ports:
  - nodePort: 30044
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    env: home
  sessionAffinity: None
status:
  loadBalancer: {}

