kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-deployment
  namespace: home
  labels:
    env: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80




