apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-deployment
  name: srv01
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
