kind: Pod
apiVersion: v1
metadata:
  name: liveness-pod-http
spec:
  containers:
    - name: nginx
      image: nginx:1.19.1
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
