apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: doudou225/nginx-varwwwhtml
        volumeMounts:
          - name: vol-cm-nginx-index
            mountPath: /var/www/html
        ports:
        - containerPort: 80
      volumes:
        - name: vol-cm-nginx-index
          configMap:
            name: cm-index-page
