kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: my-daemonsets
spec:
  selector:
    matchLabels:
      app: my-daemonset
  template:
    metadata:
      labels:
        app: my-daemonset
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.1
