apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    type: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/mnt/nfs/webfiles"
    server: nas

